//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalDavSynchronizer.OAuth.Swisscom.Globalization {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalDavSynchronizer.OAuth.Swisscom.Globalization.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Authentication successful. ähnelt.
        /// </summary>
        public static string LABEL_AUTH_OK {
            get {
                return ResourceManager.GetString("LABEL_AUTH_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string LABEL_BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("LABEL_BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string LABEL_BUTTON_OK {
            get {
                return ResourceManager.GetString("LABEL_BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;html&gt;&lt;meta charset=&quot;UTF - 8&quot;&gt;&lt;head&gt;&lt;title&gt;Swisscom OAuth 2.0&lt;/title&gt;&lt;/head&gt;&lt;body&gt;Received verification code. You may now close this window.&lt;/body&gt;&lt;/html&gt; ähnelt.
        /// </summary>
        public static string LABEL_CLOSE_AUTH_WINDOW {
            get {
                return ResourceManager.GetString("LABEL_CLOSE_AUTH_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Customer Center ähnelt.
        /// </summary>
        public static string LABEL_CUSTOMER_CENTER {
            get {
                return ResourceManager.GetString("LABEL_CUSTOMER_CENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string LABEL_ERROR {
            get {
                return ResourceManager.GetString("LABEL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Telephone book contacts ähnelt.
        /// </summary>
        public static string LABEL_HELP_LINK_NAME {
            get {
                return ResourceManager.GetString("LABEL_HELP_LINK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die https://www.swisscom.ch/en/residential/help/fixed-network/phone-number.html#Telephone_book_contacts ähnelt.
        /// </summary>
        public static string LABEL_HELP_LINK_URL {
            get {
                return ResourceManager.GetString("LABEL_HELP_LINK_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Location ähnelt.
        /// </summary>
        public static string LABEL_LOCATION {
            get {
                return ResourceManager.GetString("LABEL_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Location Selection ähnelt.
        /// </summary>
        public static string LABEL_LOCATION_SELECTION {
            get {
                return ResourceManager.GetString("LABEL_LOCATION_SELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die More information can be found here: ähnelt.
        /// </summary>
        public static string LABEL_MORE_INFO {
            get {
                return ResourceManager.GetString("LABEL_MORE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No addressbook could be found, please try again later. ähnelt.
        /// </summary>
        public static string LABEL_NO_ADDRESSBOOK_FOUND {
            get {
                return ResourceManager.GetString("LABEL_NO_ADDRESSBOOK_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select a location ähnelt.
        /// </summary>
        public static string LABEL_PLEASE_SELECT_LOCATION {
            get {
                return ResourceManager.GetString("LABEL_PLEASE_SELECT_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Be or not to be ähnelt.
        /// </summary>
        public static string LABEL_TEST {
            get {
                return ResourceManager.GetString("LABEL_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error has occured, please try again later. ähnelt.
        /// </summary>
        public static string LABEL_UNEXPECTED_ERROR {
            get {
                return ResourceManager.GetString("LABEL_UNEXPECTED_ERROR", resourceCulture);
            }
        }
    }
}
