//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalDavSynchronizer.OAuth.Swisscom.Globalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalDavSynchronizer.OAuth.Swisscom.Globalization.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LABEL_BUTTON_CANCEL {
            get {
                return ResourceManager.GetString("LABEL_BUTTON_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string LABEL_BUTTON_OK {
            get {
                return ResourceManager.GetString("LABEL_BUTTON_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Center.
        /// </summary>
        public static string LABEL_CUSTOMER_CENTER {
            get {
                return ResourceManager.GetString("LABEL_CUSTOMER_CENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string LABEL_ERROR {
            get {
                return ResourceManager.GetString("LABEL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone book contacts.
        /// </summary>
        public static string LABEL_HELP_LINK_NAME {
            get {
                return ResourceManager.GetString("LABEL_HELP_LINK_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.swisscom.ch/en/residential/help/fixed-network/phone-number.html#Telephone_book_contacts.
        /// </summary>
        public static string LABEL_HELP_LINK_URL {
            get {
                return ResourceManager.GetString("LABEL_HELP_LINK_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string LABEL_LOCATION {
            get {
                return ResourceManager.GetString("LABEL_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Selection.
        /// </summary>
        public static string LABEL_LOCATION_SELECTION {
            get {
                return ResourceManager.GetString("LABEL_LOCATION_SELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More information can be found here:.
        /// </summary>
        public static string LABEL_MORE_INFO {
            get {
                return ResourceManager.GetString("LABEL_MORE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No addressbook could be found, please try again later..
        /// </summary>
        public static string LABEL_NO_ADDRESSBOOK_FOUND {
            get {
                return ResourceManager.GetString("LABEL_NO_ADDRESSBOOK_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a location.
        /// </summary>
        public static string LABEL_PLEASE_SELECT_LOCATION {
            get {
                return ResourceManager.GetString("LABEL_PLEASE_SELECT_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be or not to be.
        /// </summary>
        public static string LABEL_TEST {
            get {
                return ResourceManager.GetString("LABEL_TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured, please try again later..
        /// </summary>
        public static string LABEL_UNEXPECTED_ERROR {
            get {
                return ResourceManager.GetString("LABEL_UNEXPECTED_ERROR", resourceCulture);
            }
        }
    }
}
